import Head from 'next/head'
import Image from 'next/image'
import Dice from '../components/Dice'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='bg-black text-white h-screen text-center py-8'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Dice />
    </div>
  )
}
